// Paste your full siteDB array here.
// Example format:

const siteDB = [
  {name:"1v1.lol",url:"https://1v1.lol/",icon:"https://1v1.lol/favicon.ico"},
{name:"Agar.io",url:"https://agar.io/?iframe=1",icon:"https://agar.io/favicon.ico"},
{name:"Airmash",url:"https://airmash.online/?embed",icon:"https://airmash.online/favicon.ico"},
{name:"AirWings.io",url:"https://airwings.io/?embed",icon:"https://airwings.io/favicon.ico"},
{name:"AntWar.io",url:"https://antwar.io/?embed",icon:"https://antwar.io/favicon.ico"},
{name:"Archers.io",url:"https://archers-io.com/embed",icon:"https://archers-io.com/favicon.ico"},
{name:"Archerz.io",url:"https://archerz.io/?embed",icon:"https://archerz.io/favicon.ico"},
{name:"Arras.io",url:"https://arras.io/",icon:"https://arras.io/favicon.ico"},
{name:"AstroRace.io",url:"https://astrorace.io/?embed",icon:"https://astrorace.io/favicon.ico"},
{name:"Backflip.io",url:"https://backflip.io/?embed",icon:"https://backflip.io/favicon.ico"},
{name:"Balloons.io",url:"https://balloons.io/?embed",icon:"https://balloons.io/favicon.ico"},
{name:"Bango.io",url:"https://bango.io/?embed",icon:"https://bango.io/favicon.ico"},
{name:"Battleboats.io",url:"https://battleboats.io/?embed",icon:"https://battleboats.io/favicon.ico"},
{name:"BattleDudes.io",url:"https://battledudes.io/?embed",icon:"https://battledudes.io/favicon.ico"},
{name:"BattleTanks.io",url:"https://battletanks.io/?embed",icon:"https://battletanks.io/favicon.ico"},
{name:"Betrayal.io",url:"https://betrayal.io/?embed",icon:"https://betrayal.io/favicon.ico"},
{name:"Bladez.io",url:"https://bladez.io/?embed",icon:"https://bladez.io/favicon.ico"},
{name:"BlockTanks.io",url:"https://blocktanks.io/?embed",icon:"https://blocktanks.io/favicon.ico"},
{name:"Boas.io",url:"https://boas.io/embed",icon:"https://boas.io/favicon.ico"},
{name:"Bonk.io",url:"https://bonk.io/gameframe",icon:"https://bonk.io/favicon.ico"},
{name:"BotBattles.io",url:"https://botbattles.io/?embed",icon:"https://botbattles.io/favicon.ico"},
{name:"Boxz.io",url:"https://boxz.io/?embed",icon:"https://boxz.io/favicon.ico"},
{name:"Brainz.io",url:"https://brainz.io/?embed",icon:"https://brainz.io/favicon.ico"},
{name:"Brawl.io",url:"https://brawl.io/?embed",icon:"https://brawl.io/favicon.ico"},
{name:"Bruh.io",url:"https://bruh.io/?embed",icon:"https://bruh.io/favicon.ico"},
{name:"BubbleTrouble.io",url:"https://bubbletrouble.io/?embed",icon:"https://bubbletrouble.io/favicon.ico"},
{name:"Bumper.io",url:"https://bumper-io.com/embed",icon:"https://bumper-io.com/favicon.ico"},
{name:"CannonBalls.io",url:"https://cannonballs.io/?embed",icon:"https://cannonballs.io/favicon.ico"},
{name:"CarArena.io",url:"https://cararena.io/?embed",icon:"https://cararena.io/favicon.ico"},
{name:"CarBoom.io",url:"https://carboom.io/?embed",icon:"https://carboom.io/favicon.ico"},
{name:"Cavegame.io",url:"https://cavegame.io/?embed",icon:"https://cavegame.io/favicon.ico"},
{name:"Chompers.io",url:"https://chompers.io/?embed",icon:"https://chompers.io/favicon.ico"},
{name:"CircleRush.io",url:"https://circlerush.io/?embed",icon:"https://circlerush.io/favicon.ico"},
{name:"ClashBlade.io",url:"https://clashblade.io/?embed",icon:"https://clashblade.io/favicon.ico"},
{name:"Colonist.io",url:"https://colonist.io/?embed",icon:"https://colonist.io/favicon.ico"},
{name:"CombatZone.io",url:"https://combatzone.io/?embed",icon:"https://combatzone.io/favicon.ico"},
{name:"Conquer.io",url:"https://conquer.io/?embed",icon:"https://conquer.io/favicon.ico"},
{name:"Craftnite.io",url:"https://craftnite.io/?embed",icon:"https://craftnite.io/favicon.ico"},
{name:"Creatur.io",url:"https://creatur.io/?embed",icon:"https://creatur.io/favicon.ico"},
{name:"CrossyCat.io",url:"https://crossycat.io/?embed",icon:"https://crossycat.io/favicon.ico"},
{name:"Crowded City",url:"https://crowdedcity.io/embed",icon:"https://crowdedcity.io/favicon.ico"},
{name:"CurveFever.io",url:"https://curvefever.io/?embed",icon:"https://curvefever.io/favicon.ico"},
{name:"DashCraft.io",url:"https://dashcraft.io/?embed",icon:"https://dashcraft.io/favicon.ico"},
{name:"Deadshot.io",url:"https://deadshot.io/?embed",icon:"https://deadshot.io/favicon.ico"},
{name:"Deeeep.io",url:"https://deeeep.io/?embed",icon:"https://deeeep.io/favicon.ico"},
{name:"Defly.io",url:"https://defly.io/?embed",icon:"https://defly.io/favicon.ico"},
{name:"Diep.io",url:"https://diep.io/?embed",icon:"https://diep.io/favicon.ico"},
{name:"DigDig.io",url:"https://digdig.io/?embed",icon:"https://digdig.io/favicon.ico"},
{name:"Dino.io",url:"https://dino.io/?embed",icon:"https://dino.io/favicon.ico"},
{name:"DinoRoyale.io",url:"https://dinoroyale.io/?embed",icon:"https://dinoroyale.io/favicon.ico"},
{name:"Dodgeballs.io",url:"https://dodgeballs.io/?embed",icon:"https://dodgeballs.io/favicon.ico"},
{name:"Dogod.io",url:"https://dogod.io/?embed",icon:"https://dogod.io/favicon.ico"},
{name:"Doomed.io",url:"https://doomed.io/?embed",icon:"https://doomed.io/favicon.ico"},
{name:"Dotz.io",url:"https://dotz.io/?embed",icon:"https://dotz.io/favicon.ico"},
{name:"Drawaria.online",url:"https://drawaria.online/?embed",icon:"https://drawaria.online/favicon.ico"},
{name:"Driftin.io",url:"https://driftin.io/?embed",icon:"https://driftin.io/favicon.ico"},
{name:"Drillz.io",url:"https://drillz.io/?embed",icon:"https://drillz.io/favicon.ico"},
{name:"Ducklings.io",url:"https://ducklings.io/?embed",icon:"https://ducklings.io/favicon.ico"},
{name:"Dynast.io",url:"https://dynast.io/?embed",icon:"https://dynast.io/favicon.ico"},
{name:"EatMe.io",url:"https://eatme.io/?embed",icon:"https://eatme.io/favicon.ico"},
{name:"Elytra.io",url:"https://elytra.io/?embed",icon:"https://elytra.io/favicon.ico"},
{name:"Empire.io",url:"https://empire.io/?embed",icon:"https://empire.io/favicon.ico"},
{name:"Escap.io",url:"https://escap.io/?embed",icon:"https://escap.io/favicon.ico"},
{name:"EvoWars.io",url:"https://evowars.io/?embed",icon:"https://evowars.io/favicon.ico"},
{name:"Fallerz.io",url:"https://fallerz.io/?embed",icon:"https://fallerz.io/favicon.ico"},
{name:"FarmingGame.io",url:"https://farminggame.io/?embed",icon:"https://farminggame.io/favicon.ico"},
{name:"Ferge.io",url:"https://ferge.io/?embed",icon:"https://ferge.io/favicon.ico"},
{name:"Fidget.io",url:"https://fidget.io/?embed",icon:"https://fidget.io/favicon.ico"},
{name:"Filler.io",url:"https://filler.io/?embed",icon:"https://filler.io/favicon.ico"},
{name:"Fisp.io",url:"https://fisp.io/?embed",icon:"https://fisp.io/favicon.ico"},
{name:"Fishz.io",url:"https://fishz.io/?embed",icon:"https://fishz.io/favicon.ico"},
{name:"FlappyRoyale.io",url:"https://flappyroyale.io/?embed",icon:"https://flappyroyale.io/favicon.ico"},
{name:"Florr.io",url:"https://florr.io/?embed",icon:"https://florr.io/favicon.ico"},
{name:"FlyOrDie.io",url:"https://flyordie.io/?embed",icon:"https://flyordie.io/favicon.ico"},
{name:"Foes.io",url:"https://foes.io/?embed",icon:"https://foes.io/favicon.ico"},
{name:"Fortz.io",url:"https://fortz.io/?embed",icon:"https://fortz.io/favicon.ico"},
{name:"FoxyLand.io",url:"https://foxyland.io/?embed",icon:"https://foxyland.io/favicon.ico"},
{name:"FrenzyFarm.io",url:"https://frenzyfarm.io/?embed",icon:"https://frenzyfarm.io/favicon.ico"},
{name:"Frogar.io",url:"https://frogar.io/?embed",icon:"https://frogar.io/favicon.ico"},
{name:"Frostbite.io",url:"https://frostbite.io/?embed",icon:"https://frostbite.io/favicon.ico"},
{name:"FruitBattle.io",url:"https://fruitbattle.io/?embed",icon:"https://fruitbattle.io/favicon.ico"},
{name:"FuryWheels.io",url:"https://furywheels.io/?embed",icon:"https://furywheels.io/favicon.ico"},
{name:"Galaxystrife",url:"https://galaxystrife.com/?embed",icon:"https://galaxystrife.com/favicon.ico"},
{name:"Gauch.io",url:"https://gauch.io/?embed",icon:"https://gauch.io/favicon.ico"},
{name:"Gats.io",url:"https://gats.io/?embed",icon:"https://gats.io/favicon.ico"},
{name:"Germs.io",url:"https://germs.io/?embed",icon:"https://germs.io/favicon.ico"},
{name:"Glor.io",url:"https://glor.io/?embed",icon:"https://glor.io/favicon.ico"},
{name:"GoBattle.io",url:"https://gobattle.io/?embed",icon:"https://gobattle.io/favicon.ico"},
{name:"GolfRoyale.io",url:"https://golfroyale.io/?embed",icon:"https://golfroyale.io/favicon.ico"},
{name:"Gota.io",url:"https://gota.io/embed",icon:"https://gota.io/favicon.ico"},
{name:"Grailz.io",url:"https://grailz.io/?embed",icon:"https://grailz.io/favicon.ico"},
{name:"Gravz.io",url:"https://gravz.io/?embed",icon:"https://gravz.io/favicon.ico"},
{name:"Greed.io",url:"https://greed.io/?embed",icon:"https://greed.io/favicon.ico"},
{name:"Gridz.io",url:"https://gridz.io/?embed",icon:"https://gridz.io/favicon.ico"},
{name:"Gulper.io",url:"https://gulper.io/?embed",icon:"https://gulper.io/favicon.ico"},
{name:"Gunfight.io",url:"https://gunfight.io/?embed",icon:"https://gunfight.io/favicon.ico"},
{name:"Gunies.io",url:"https://gunies.io/?embed",icon:"https://gunies.io/favicon.ico"},
{name:"Guns.lol",url:"https://guns.lol/?embed",icon:"https://guns.lol/favicon.ico"},
{name:"Hackerz.io",url:"https://hackerz.io/?embed",icon:"https://hackerz.io/favicon.ico"},
{name:"HaxBall",url:"https://haxball.com/?embed",icon:"https://haxball.com/favicon.ico"},
{name:"Heartz.io",url:"https://heartz.io/?embed",icon:"https://heartz.io/favicon.ico"},
{name:"Hexanaut.io",url:"https://hexanaut.io/?embed",icon:"https://hexanaut.io/favicon.ico"},
{name:"Hexar.io",url:"https://hexar.io/?embed",icon:"https://hexar.io/favicon.ico"},
{name:"HexArena.io",url:"https://hexarena.io/?embed",icon:"https://hexarena.io/favicon.ico"},
{name:"Hilly.io",url:"https://hilly.io/?embed",icon:"https://hilly.io/favicon.ico"},
{name:"Hoard.io",url:"https://hoard.io/?embed",icon:"https://hoard.io/favicon.ico"},
{name:"Hockey.io",url:"https://hockey.io/?embed",icon:"https://hockey.io/favicon.ico"},
{name:"Hordes.io",url:"https://hordes.io/?embed",icon:"https://hordes.io/favicon.ico"},
{name:"HorseRun.io",url:"https://horserun.io/?embed",icon:"https://horserun.io/favicon.ico"},
{name:"HoverSkate.io",url:"https://hoverskate.io/?embed",icon:"https://hoverskate.io/favicon.ico"},
{name:"HungryShark.io",url:"https://hungryshark.io/?embed",icon:"https://hungryshark.io/favicon.ico"},
{name:"Huntz.io",url:"https://huntz.io/?embed",icon:"https://huntz.io/favicon.ico"},
{name:"HyperFleet.io",url:"https://hyperfleet.io/?embed",icon:"https://hyperfleet.io/favicon.ico"},
{name:"IceDodo.io",url:"https://icedodo.io/?embed",icon:"https://icedodo.io/favicon.ico"},
{name:"IceHole.io",url:"https://icehole.io/?embed",icon:"https://icehole.io/favicon.ico"},
{name:"IdleBreakout.io",url:"https://idlebreakout.io/?embed",icon:"https://idlebreakout.io/favicon.ico"},
{name:"IdlePlanet.io",url:"https://idleplanet.io/?embed",icon:"https://idleplanet.io/favicon.ico"},
{name:"Imposter.io",url:"https://imposter.io/?embed",icon:"https://imposter.io/favicon.ico"},
{name:"InkWars.io",url:"https://inkwars.io/?embed",icon:"https://inkwars.io/favicon.ico"},
{name:"Islandz.io",url:"https://islandz.io/?embed",icon:"https://islandz.io/favicon.ico"},
{name:"Javelin.io",url:"https://javelin.io/?embed",icon:"https://javelin.io/favicon.ico"},
{name:"JetRush.io",url:"https://jetrush.io/?embed",icon:"https://jetrush.io/favicon.ico"},
{name:"Joust.io",url:"https://joust.io/?embed",icon:"https://joust.io/favicon.ico"},
{name:"Jumper.io",url:"https://jumper.io/?embed",icon:"https://jumper.io/favicon.ico"},
{name:"JungleRun.io",url:"https://junglerun.io/?embed",icon:"https://junglerun.io/favicon.ico"},
{name:"JustFall.lol",url:"https://justfall.lol/?embed",icon:"https://justfall.lol/favicon.ico"},
{name:"Karnage.io",url:"https://karnage.io/?embed",icon:"https://karnage.io/favicon.ico"},
{name:"KartWars.io",url:"https://kartwars.io/?embed",icon:"https://kartwars.io/favicon.ico"},
{name:"Krunker.io",url:"https://krunker.io/?game=embed",icon:"https://krunker.io/favicon.ico"},
{name:"Kugeln.io",url:"https://kugeln.io/?embed",icon:"https://kugeln.io/favicon.ico"},
{name:"Limax.io",url:"https://limax.io/?embed",icon:"https://limax.io/favicon.ico"},
{name:"LittleWarGame",url:"https://littlewargame.com/",icon:"https://littlewargame.com/favicon.ico"},
{name:"Lordz.io",url:"https://lordz.io/?embed",icon:"https://lordz.io/favicon.ico"},
{name:"MiniGiants.io",url:"https://minigiants.io/?embed",icon:"https://minigiants.io/favicon.ico"},
{name:"MobSmash.io",url:"https://mobsmash.io/?embed",icon:"https://mobsmash.io/favicon.ico"},
{name:"Mope.io",url:"https://mope.io/?embed",icon:"https://mope.io/favicon.ico"},
{name:"MotoArena.io",url:"https://motoarena.io/?embed",icon:"https://motoarena.io/favicon.ico"},
{name:"MotoX3M.io",url:"https://motox3m.io/?embed",icon:"https://motox3m.io/favicon.ico"},
{name:"Mushroom.io",url:"https://mushroom.io/?embed",icon:"https://mushroom.io/favicon.ico"},
{name:"Narwhale.io",url:"https://narwhale.io/?embed",icon:"https://narwhale.io/favicon.ico"},
{name:"Nightpoint.io",url:"https://nightpoint.io/?embed",icon:"https://nightpoint.io/favicon.ico"},
{name:"Oceanar.io",url:"https://oceanar.io/?embed",icon:"https://oceanar.io/favicon.ico"},
{name:"Orb.io",url:"https://orb-io.com/embed",icon:"https://orb-io.com/favicon.ico"},
{name:"Paper.io2",url:"https://paper-io.com/embed",icon:"https://paper-io.com/favicon.ico"},
{name:"Pikes.io",url:"https://pikes.io/?embed",icon:"https://pikes.io/favicon.ico"},
{name:"PirateBattle.io",url:"https://piratebattle.io/?embed",icon:"https://piratebattle.io/favicon.ico"},
{name:"PixelWarfare",url:"https://pixel-warfare.com/gameframe",icon:"https://pixel-warfare.com/favicon.ico"},
{name:"Powerline.io",url:"https://powerline.io/?embed",icon:"https://powerline.io/favicon.ico"},
{name:"RaceTime.io",url:"https://racetime.io/?embed",icon:"https://racetime.io/favicon.ico"},
{name:"Raaaaft.io",url:"https://raaaaft.io/?embed",icon:"https://raaaaft.io/favicon.ico"},
{name:"RocketBlitz",url:"https://rocketblitz.com/?embed",icon:"https://rocketblitz.com/favicon.ico"},
{name:"RocketBotRoyale",url:"https://rocketbotroyale.winterpixel.io/?embed",icon:"https://rocketbotroyale.winterpixel.io/favicon.ico"},
{name:"RushTeam",url:"https://rushteam.com/?embed",icon:"https://rushteam.com/favicon.ico"},
{name:"ShellShockers",url:"https://shellshock.io/?embed",icon:"https://shellshock.io/favicon.ico"},
{name:"Shooters.io",url:"https://shooters.io/?embed",icon:"https://shooters.io/favicon.ico"},
{name:"SkyRoyale.io",url:"https://skyroyale.io/?embed",icon:"https://skyroyale.io/favicon.ico"},
{name:"Slither.io",url:"https://slither.io/embed",icon:"https://slither.io/favicon.ico"},
{name:"SmashKarts.io",url:"https://smashkarts.io/",icon:"https://smashkarts.io/favicon.ico"},
{name:"Snowball.io",url:"https://snowball-io.io/embed",icon:"https://snowball-io.io/favicon.ico"},
{name:"Splix.io",url:"https://splix.io/?embed",icon:"https://splix.io/favicon.ico"},
{name:"Squadd.io",url:"https://squadd.io/?embed",icon:"https://squadd.io/favicon.ico"},
{name:"Starblast.io",url:"https://starblast.io/?embed",icon:"https://starblast.io/favicon.ico"},
{name:"Starve.io",url:"https://starve.io/?embed",icon:"https://starve.io/favicon.ico"},
{name:"Superhex.io",url:"https://superhex.io/?embed",icon:"https://superhex.io/favicon.ico"},
{name:"Swordz.io",url:"https://swordz.io/?embed",icon:"https://swordz.io/favicon.ico"},
{name:"TacticsCore.io",url:"https://tacticscore.io/",icon:"https://tacticscore.io/favicon.ico"},
{name:"TankRoyale.io",url:"https://tankroyale.io/?embed",icon:"https://tankroyale.io/favicon.ico"},
{name:"TileMan.io",url:"https://tileman.io/?embed",icon:"https://tileman.io/favicon.ico"},
{name:"Trapz.io",url:"https://trapz.io/?embed",icon:"https://trapz.io/favicon.ico"},
{name:"TreasureArena",url:"https://treasurearena.com/?embed",icon:"https://treasurearena.com/favicon.ico"},
{name:"Vertix.io",url:"https://vertix.io/?embed",icon:"https://vertix.io/favicon.ico"},
{name:"Warbot.io",url:"https://warbot.io/?embed",icon:"https://warbot.io/favicon.ico"},
{name:"WarCall.io",url:"https://warcall.io/?embed",icon:"https://warcall.io/favicon.ico"},
{name:"Wings.io",url:"https://wings.io/?embed",icon:"https://wings.io/favicon.ico"},
{name:"Wormax.io",url:"https://wormax.io/?embed",icon:"https://wormax.io/favicon.ico"},
{name:"Wormate.io",url:"https://wormate.io/embed",icon:"https://wormate.io/favicon.ico"},
{name:"Xess.io",url:"https://xess.io/?embed",icon:"https://xess.io/favicon.ico"},
{name:"Yohoho.io",url:"https://yohoho.io/?embed",icon:"https://yohoho.io/favicon.ico"},
{name:"Zlap.io",url:"https://zlap.io/?embed",icon:"https://zlap.io/favicon.ico"},
{name:"ZombsRoyale.io",url:"https://zombsroyale.io/?embed",icon:"https://zombsroyale.io/favicon.ico"},
{name:"Zomzom.io",url:"https://zomzom.io/?embed",icon:"https://zomzom.io/favicon.ico"},
{name:"MergeSimulator",url:"https://mergesimulator.io"},
{name:"MergeWars",url:"https://mergewars.io"},
{name:"MicroGravity",url:"https://microgravity.io"},
{name:"MineBlocks",url:"https://mineblocks.com"},
{name:"MineClicker",url:"https://mineclicker.io"},
{name:"MineEnergy",url:"https://mineenergy.io"},

{name:"MineParkour",url:"https://mineparkour.io"},
{name:"MineRunner",url:"https://minerunner.io"},
{name:"MiniGiants",url:"https://minigiants.io"},
{name:"MiniRoyale",url:"https://miniroyale2.io"},
{name:"MiniSoccer",url:"https://minisoccer.io"},
{name:"MobCity",url:"https://mobcity.com"},

{name:"MonkeyMart",url:"https://monkeymart.io"},
{name:"MonsterTracks",url:"https://monstertracks.io"},
{name:"MotoManiacs",url:"https://motomaniacs.io"},
{name:"MotoX3M2",url:"https://motox3m2.com"},
{name:"MotoX3MPool",url:"https://motox3mpool.com"},
{name:"MotoX3MWinter",url:"https://motox3mwinter.com"},

{name:"MrBullet",url:"https://mrbullet.io"},
{name:"MutilateADoll",url:"https://mutilateadoll.io"},
{name:"MyFarm",url:"https://myfarm.io"},
{name:"MyLittlePonyRunner",url:"https://mlprunner.com"},
{name:"NarrowOne",url:"https://narrow.one"},
{name:"NeonBlaster",url:"https://neonblaster.io"},

{name:"NeonBiker",url:"https://neonbiker.io"},
{name:"NeonRace",url:"https://neonrace.io"},
{name:"NeonTank",url:"https://neontank.io"},
{name:"NightDrift",url:"https://nightdrift.io"},
{name:"NinjaClashHeroes",url:"https://ninjaclashheroes.io"},
{name:"NinjaHands",url:"https://ninjahands.io"},

{name:"NinjaRun",url:"https://ninjarun.io"},
{name:"NoobVsPro",url:"https://noobvspro.io"},
{name:"NuggetRoyale",url:"https://nuggetroyale.io"},
{name:"Oceanar.io",url:"https://oceanar.io"},
{name:"OddbodsTurbo",url:"https://oddbodsturbo.com"},
{name:"OmNomRun",url:"https://omnomrun.io"},

{name:"OneMoreDash",url:"https://onemoredash.io"},
{name:"OneMoreLevel",url:"https://onemorelevel.com"},
{name:"OneNightAtFlumpty",url:"https://onenightatflumpty.com"},
{name:"OpenArena",url:"https://openarena.io"},
{name:"OrbitalSurvival",url:"https://orbitalsurvival.io"},
{name:"Outlive",url:"https://outlive.io"},

{name:"Pacman",url:"https://pacman.io"},
{name:"Paint.io",url:"https://paint-io.com"},
{name:"Pandemic2",url:"https://pandemic2.io"},
{name:"ParkourBlock3D",url:"https://parkourblock3d.com"},
{name:"ParkourRace",url:"https://parkourrace.io"},
{name:"PartyToons",url:"https://partytoons.io"},

{name:"PenguinDiner",url:"https://penguindiner.io"},
{name:"PenguinDiner2",url:"https://penguindiner2.io"},
{name:"PerfectDrift",url:"https://perfectdrift.io"},
{name:"PickCrafter",url:"https://pickcrafter.io"},
{name:"PixelCombat2",url:"https://pixelcombat2.com"},
{name:"PixelForces",url:"https://pixelforces.io"},

{name:"PixelGunSurvival",url:"https://pixelgunsurvival.io"},
{name:"PixelRacers",url:"https://pixelracers.io"},
{name:"PixelSpeedrun",url:"https://pixelspeedrun.com"},
{name:"PizzaTower",url:"https://pizzatower.io"},
{name:"PlazmaBurst",url:"https://plazmaburst.io"},
{name:"PlazmaBurst2",url:"https://plazmaburst2.io"},

{name:"PolyTrack2",url:"https://polytrack2.io"},
{name:"PoolClub",url:"https://poolclub.io"},
{name:"PoolRush",url:"https://poolrush.io"},
{name:"Portal2D",url:"https://portal2d.com"},
{name:"PortalRunner",url:"https://portalrunner.io"},
{name:"PowerBadminton",url:"https://powerbadminton.com"},

{name:"PowerWings",url:"https://powerwings.io"},
{name:"Punchers",url:"https://punchers.io"},
{name:"PushEmAll",url:"https://pushemall.io"},
{name:"PuzzleGuys",url:"https://puzzleguys.io"},
{name:"QuickDraw",url:"https://quickdraw.io"},
{name:"RabbidsWildRace",url:"https://rabbidswildrace.com"},
{name:"RacingLimits",url:"https://racinglimits.io"},
{name:"RacingRocket",url:"https://racingrocket.io"},
{name:"RagdollArchers",url:"https://ragdollarchers.io"},
{name:"RagdollHit",url:"https://ragdollhit.io"},
{name:"RagdollRunners",url:"https://ragdollrunners.io"},
{name:"RaftWars",url:"https://raftwars.io"},

{name:"RaftWars2",url:"https://raftwars2.io"},
{name:"Railbound",url:"https://railbound.io"},
{name:"RainbowObby",url:"https://rainbowobby.com"},
{name:"RallyPoint",url:"https://rallypoint.io"},
{name:"RanchSimulator",url:"https://ranchsimulator.io"},
{name:"RangerSteve",url:"https://rangersteve.io"},

{name:"RatsInvasion",url:"https://ratsinvasion.io"},
{name:"RealCars",url:"https://realcars.io"},
{name:"RealDrift",url:"https://realdrift.io"},
{name:"RealFlight",url:"https://realflight.io"},
{name:"RealisticCarCrash",url:"https://realisticcarcrash.com"},
{name:"RebelForces",url:"https://rebelforces.io"},

{name:"RedBall",url:"https://redball.io"},
{name:"RedBall4",url:"https://redball4.io"},
{name:"RedDriver",url:"https://reddriver.io"},
{name:"RedPandaSurvival",url:"https://redpandasurvival.io"},
{name:"RedVsBlue",url:"https://redvsblue.io"},
{name:"RevolutionRacing",url:"https://revolutionracing.io"},

{name:"RiddleSchool",url:"https://riddleschool.io"},
{name:"RiddleSchool2",url:"https://riddleschool2.io"},
{name:"RiddleSchool3",url:"https://riddleschool3.io"},
{name:"RiddleSchool4",url:"https://riddleschool4.io"},
{name:"RiddleSchool5",url:"https://riddleschool5.io"},
{name:"RiddleTransfer",url:"https://riddletransfer.io"},

{name:"RiddleTransfer2",url:"https://riddletransfer2.io"},
{name:"RiotEscape",url:"https://riotescape.io"},
{name:"RisingCities",url:"https://risingcities.io"},
{name:"RivalStars",url:"https://rivalstars.io"},
{name:"RoadCrash",url:"https://roadcrash.io"},
{name:"RoadMadness",url:"https://roadmadness.io"},

{name:"RoadRash",url:"https://roadrash.io"},
{name:"RoadSmash",url:"https://roadsmash.io"},
{name:"Robostorm",url:"https://robostorm.io"},
{name:"RocketClash3D",url:"https://rocketclash3d.io"},
{name:"RocketLeague2D",url:"https://rocketleague2d.com"},
{name:"RooftopSnipers",url:"https://rooftopsnipers.io"},

{name:"RooftopSnipers2",url:"https://rooftopsnipers2.io"},
{name:"RoomClicker",url:"https://roomclicker.io"},
{name:"RopeHelp",url:"https://ropehelp.io"},
{name:"RopeManRun",url:"https://ropemanrun.io"},
{name:"RopeSlash",url:"https://ropeslash.io"},
{name:"RopeSwing",url:"https://ropeswing.io"},

{name:"Run1",url:"https://run1.io"},
{name:"Run2",url:"https://run2.io"},
{name:"Run4",url:"https://run4.io"},
{name:"RunBoys",url:"https://runboys.io"},
{name:"RunRace3D",url:"https://runrace3d.io"},
{name:"RunRich3D",url:"https://runrich3d.io"},

{name:"RushTeam",url:"https://rushteam.io"},
{name:"RustyLake",url:"https://rustylake.com"},
{name:"SaberClash",url:"https://saberclash.io"},
{name:"SafariRace",url:"https://safarirace.io"},
{name:"SandStrike",url:"https://sandstrike.io"},
{name:"SantaRun",url:"https://santarun.io"},

{name:"SausageFlip",url:"https://sausageflip.io"},
{name:"SchoolBreakout",url:"https://schoolbreakout.io"},
{name:"SchoolBusRacing",url:"https://schoolbusracing.io"},
{name:"ScorchingWheels",url:"https://scorchingwheels.io"},
{name:"ScrapMetal2",url:"https://scrapmetal2.com"},
{name:"ScrapMetal4",url:"https://scrapmetal4.com"},

{name:"SeaDragons",url:"https://seadragons.io"},
{name:"SeaOfWords",url:"https://seaofwords.io"},
{name:"SeaWars",url:"https://seawars.io"},
{name:"SharkAttack",url:"https://sharkattack.io"},
{name:"SharkGame",url:"https://sharkgame.io"},
{name:"Shark.io",url:"https://shark-io.com"},

{name:"ShootEm",url:"https://shootem.io"},
{name:"ShootersArena",url:"https://shootersarena.io"},
{name:"ShortLife",url:"https://shortlife.io"},
{name:"ShortLife2",url:"https://shortlife2.io"},
{name:"ShortRide",url:"https://shortride.io"},
{name:"ShotgunArena",url:"https://shotgunarena.io"},
{name:"ShrinkMe",url:"https://shrinkme.io"},
{name:"SideArms",url:"https://sidearms.io"},
{name:"SiegeOnline",url:"https://siegeonline.com"},
{name:"SiftHeads",url:"https://siftheads.io"},
{name:"SillySnakes",url:"https://sillysnakes.io"},
{name:"SimplePlanes",url:"https://simpleplanes.com"},

{name:"SimpleRockets",url:"https://simplerockets.com"},
{name:"SirenHead",url:"https://sirenhead.io"},
{name:"SkyBlock",url:"https://skyblock.io"},
{name:"SkyMad",url:"https://skymad.io"},
{name:"SkyRiders",url:"https://skyriders.io"},
{name:"SkyWars",url:"https://skywars.io"},

{name:"SlapKings",url:"https://slapkings.io"},
{name:"SlideInTheWoods",url:"https://slideinthewoods.com"},
{name:"SlopeBall",url:"https://slopeball.io"},
{name:"SlopeCity",url:"https://slopecity.io"},
{name:"SlopeTunnel",url:"https://slopetunnel.io"},
{name:"SmashArena",url:"https://smasharena.io"},

{name:"SmashHit",url:"https://smashhit.io"},
{name:"SmashyCity",url:"https://smashycity.io"},
{name:"Snake.is",url:"https://snake.is"},
{name:"SnakeGame",url:"https://snakegame.io"},
{name:"SnakeWorm",url:"https://snakeworm.io"},
{name:"SneakySasquatch",url:"https://sneakysasquatch.io"},

{name:"SoccerHeads",url:"https://soccerheads.io"},
{name:"SoccerPhysics",url:"https://soccerphysics.io"},
{name:"Solitaire",url:"https://solitaire.com"},
{name:"SolitaireClassic",url:"https://solitaireclassic.com"},
{name:"SolitaireOnline",url:"https://solitaireonline.com"},
{name:"SoulKnight",url:"https://soulknight.io"},

{name:"SpaceAdventures",url:"https://spaceadventures.io"},
{name:"SpaceArena",url:"https://spacearena.io"},
{name:"SpaceBattle",url:"https://spacebattle.io"},
{name:"SpaceInvaders",url:"https://spaceinvaders.io"},
{name:"SpaceRacers",url:"https://spaceracers.io"},
{name:"SpaceRiders",url:"https://spaceriders.io"},

{name:"SpeedBoat",url:"https://speedboat.io"},
{name:"SpeedDrifters",url:"https://speeddrifters.io"},
{name:"SpeedRacing",url:"https://speedracing.io"},
{name:"SpeedRun4",url:"https://speedrun4.com"},
{name:"SpeedyGolf",url:"https://speedygolf.io"},
{name:"SpeedyRoad",url:"https://speedyroad.io"},

{name:"SpiderFighter",url:"https://spiderfighter.io"},
{name:"SpiderHero",url:"https://spiderhero.io"},
{name:"SpiderSwing",url:"https://spiderswing.io"},
{name:"SpinMaster",url:"https://spinmaster.io"},
{name:"Spinz.io",url:"https://spinz.io"},
{name:"SplashCars",url:"https://splashcars.io"},

{name:"Splix.io",url:"https://splix.io"},
{name:"SportsHeads",url:"https://sportsheads.io"},
{name:"SprintClub",url:"https://sprintclub.io"},
{name:"SpyCar",url:"https://spycar.io"},
{name:"SquidGame",url:"https://squidgame.io"},
{name:"StackBall",url:"https://stackball.io"},

{name:"StackColors",url:"https://stackcolors.io"},
{name:"StackyBird",url:"https://stackybird.io"},
{name:"Starve.io",url:"https://starve.io"},
{name:"StickArchers",url:"https://stickarchers.io"},
{name:"StickBattle",url:"https://stickbattle.io"},
{name:"StickClash",url:"https://stickclash.io"},

{name:"StickDuel",url:"https://stickduel.io"},
{name:"StickFight",url:"https://stickfight.io"},
{name:"StickmanBoost",url:"https://stickmanboost.io"},
{name:"StickmanClimb",url:"https://stickmanclimb.io"},
{name:"StickmanHook2",url:"https://stickmanhook2.io"},
{name:"StickmanParkour",url:"https://stickmanparkour.io"},

{name:"StickmanRagdoll",url:"https://stickmanragdoll.io"},
{name:"StickmanRun",url:"https://stickmanrun.io"},
{name:"StickmanSupreme2",url:"https://stickmansupreme2.com"},
{name:"StickmanWarriors",url:"https://stickmanwarriors.io"},
{name:"StiltFella",url:"https://stiltfella.io"},
{name:"Stomped",url:"https://stomped.io"},

{name:"StoneIdle",url:"https://stoneidle.io"},
{name:"StormTheHouse",url:"https://stormthehouse.io"},
{name:"StreetFighterOnline",url:"https://streetfighteronline.com"},
{name:"StrikeForceHeroes",url:"https://strikeforceheroes.io"},
{name:"StrikeForceHeroes2",url:"https://strikeforceheroes2.io"},
{name:"SubwaySurfers",url:"https://subwaysurfers.io"},

{name:"Sudoku",url:"https://sudoku.com"},
{name:"SugarSugar",url:"https://sugarsugar.io"},
{name:"SuperBikeHero",url:"https://superbikehero.io"},
{name:"SuperFighters",url:"https://superfighters.io"},
{name:"SuperHot",url:"https://superhot.io"},
{name:"SuperMario",url:"https://supermario.io"},
{name:"SuperMarioBros",url:"https://supermariobros.io"},
{name:"SuperMarioFlash",url:"https://supermarioflash.io"},
{name:"SuperMarioRun",url:"https://supermariorun.io"},
{name:"SuperMechs",url:"https://supermechs.com"},
{name:"SuperRacer",url:"https://superracer.io"},
{name:"SuperSmashFlash",url:"https://supersmashflash.io"},

{name:"SuperSmashFlash2",url:"https://supersmashflash2.io"},
{name:"SuperSpeed",url:"https://superspeed.io"},
{name:"SuperStarCar",url:"https://superstarcar.io"},
{name:"SuperSudoku",url:"https://supersudoku.com"},
{name:"SuperTanks",url:"https://supertanks.io"},
{name:"SuperTruck",url:"https://supertruck.io"},

{name:"SurferBros",url:"https://surferbros.io"},
{name:"SurvivalRace",url:"https://survivalrace.io"},
{name:"SurvivalSimulator",url:"https://survivalsimulator.io"},
{name:"SurvivorIdle",url:"https://survivoridle.io"},
{name:"SwarmSimulator",url:"https://swarmsimulator.io"},
{name:"SweetRun",url:"https://sweetrun.io"},

{name:"SwordBattle",url:"https://swordbattle.io"},
{name:"SwordMasters",url:"https://swordmasters.io"},
{name:"SwordsAndSandals",url:"https://swordsandsandals.com"},
{name:"SwordsAndSouls",url:"https://swordsandsouls.io"},
{name:"TableTennis",url:"https://tabletennis.io"},
{name:"TankBattle",url:"https://tankbattle.io"},

{name:"TankCraft",url:"https://tankcraft.io"},
{name:"TankFury",url:"https://tankfury.io"},
{name:"TankHit",url:"https://tankhit.io"},
{name:"TankMania",url:"https://tankmania.io"},
{name:"TankOff",url:"https://tankoff.com"},
{name:"TankOff2",url:"https://tankoff2.com"},

{name:"TankRoyale",url:"https://tankroyale.io"},
{name:"TankStars",url:"https://tankstars.io"},
{name:"TapTapShots",url:"https://taptapshots.io"},
{name:"TaxiRun",url:"https://taxirun.io"},
{name:"TempleRun2D",url:"https://templerun2d.com"},
{name:"TempleRunOnline",url:"https://templerunonline.io"},

{name:"TennisMasters",url:"https://tennismasters.io"},
{name:"TennisOpen",url:"https://tennisopen.io"},
{name:"TetrisClassic",url:"https://tetrisclassic.com"},
{name:"TheBindingOfIsaac",url:"https://thebindingofisaac.io"},
{name:"TheFloorIsLava",url:"https://thefloorislava.io"},
{name:"TheHeist",url:"https://theheist.io"},

{name:"TheLastStand",url:"https://thelaststand.io"},
{name:"TheLastStandUnionCity",url:"https://thelaststandunioncity.com"},
{name:"TheLegendOfZelda2D",url:"https://thelegendofzelda.io"},
{name:"TheMaze",url:"https://themaze.io"},
{name:"TheRoom",url:"https://theroom.io"},
{name:"TheWalkingMerge",url:"https://thewalkingmerge.com"},

{name:"ThiefPuzzle",url:"https://thiefpuzzle.io"},
{name:"ThingThingArena",url:"https://thingthingarena.io"},
{name:"ThisIsTheOnlyLevel",url:"https://thisistheonlylevel.io"},
{name:"ThrillRush",url:"https://thrillrush.io"},
{name:"ThunderCars",url:"https://thundercars.io"},
{name:"ThunderPlane",url:"https://thunderplane.io"},

{name:"TimeShooter",url:"https://timeshooter.io"},
{name:"TimeShooter2",url:"https://timeshooter2.io"},
{name:"TimeShooter3",url:"https://timeshooter3.io"},
{name:"TinyCrashFighters",url:"https://tinycrashfighters.io"},
{name:"TinyRacers",url:"https://tinyracers.io"},
{name:"TinyTown",url:"https://tinytown.io"},

{name:"TitaniumRacer",url:"https://titaniumracer.io"},
{name:"TombRunner",url:"https://tombrunner.io"},
{name:"TopDownSurvival",url:"https://topdownsurvival.io"},
{name:"TopGuns",url:"https://topguns.io"},
{name:"TopSpeed",url:"https://topspeed.io"},
{name:"TossTheTurtle",url:"https://tosstheturtle.io"},

{name:"TowerDefense",url:"https://towerdefense.com"},
{name:"TowerDefense2",url:"https://towerdefense2.com"},
{name:"TowerOfDestiny",url:"https://towerofdestiny.io"},
{name:"Townscaper",url:"https://townscaper.io"},
{name:"TrafficMania",url:"https://trafficmania.io"},
{name:"TrafficRun",url:"https://trafficrun.io"},

{name:"TrafficRider",url:"https://trafficrider.io"},
{name:"TrafficSim",url:"https://trafficsim.io"},
{name:"TrainSurfers",url:"https://trainsurfers.io"},
{name:"TrainTaxi",url:"https://traintaxi.io"},
{name:"TrapAdventure",url:"https://trapadventure.io"},
{name:"TrexRunner",url:"https://trexrunner.com"},

{name:"TribalWars",url:"https://tribalwars.net"},
{name:"TrickShot",url:"https://trickshot.io"},
{name:"TrickyTowers",url:"https://trickytowers.io"},
{name:"TruckLoader",url:"https://truckloader.io"},
{name:"TruckLoader2",url:"https://truckloader2.io"},
{name:"TunnelGlider",url:"https://tunnelglider.io"},
{name:"TurboMotoRacer",url:"https://turbomotoracer.io"},
{name:"TurboStars",url:"https://turbostars.io"},
{name:"TurboWarp",url:"https://turbowarp.org"},
{name:"TurnRight",url:"https://turnright.io"},
{name:"TurtleRun",url:"https://turtlerun.io"},
{name:"TwoBall3D",url:"https://twoball3d.com"},

{name:"TwoPlayerGames",url:"https://twoplayergames.org"},
{name:"UltimateCarDriving",url:"https://ultimatecardriving.com"},
{name:"UltimateChess",url:"https://ultimatechess.io"},
{name:"UltimateGolf",url:"https://ultimategolf.io"},
{name:"UltimateRacing",url:"https://ultimateracing.io"},
{name:"UltimateTicTacToe",url:"https://ultimatetictactoe.io"},

{name:"UltraDrift",url:"https://ultradrift.io"},
{name:"UnblockMe",url:"https://unblockme.io"},
{name:"UnderwaterWars",url:"https://underwaterwars.io"},
{name:"UnicycleHero",url:"https://unicyclehero.io"},
{name:"UnicycleLegend",url:"https://unicyclelegend.io"},
{name:"UnicycleMayhem",url:"https://unicyclemayhem.io"},

{name:"UnfairMario",url:"https://unfairmario.org"},
{name:"UnicycleRace",url:"https://unicyclerace.io"},
{name:"UniverseGun",url:"https://universegun.io"},
{name:"UnoOnline",url:"https://uno-online.com"},
{name:"UpHillRacing",url:"https://uphillracing.io"},
{name:"UrbanSniper",url:"https://urbansniper.io"},

{name:"UrbanStack",url:"https://urbanstack.io"},
{name:"VampireSurvivors",url:"https://vampiresurvivors.io"},
{name:"VectorRush",url:"https://vectorrush.io"},
{name:"VehicleMasters",url:"https://vehiclemasters.io"},
{name:"VelocityRacers",url:"https://velocityracers.io"},
{name:"Vex8",url:"https://vex8.io"},

{name:"VikingAttack",url:"https://vikingattack.io"},
{name:"VikingVillage",url:"https://vikingvillage.io"},
{name:"VillageDefense",url:"https://villagedefense.io"},
{name:"Vortex9",url:"https://vortex9.io"},
{name:"VoxelCraft",url:"https://voxelcraft.io"},
{name:"VoxelFly",url:"https://voxelfly.io"},

{name:"VoxelRacers",url:"https://voxelracers.io"},
{name:"VRally",url:"https://vrally.io"},
{name:"WackyRaces",url:"https://wackyraces.io"},
{name:"WarCall",url:"https://warcall.io"},
{name:"WarClash",url:"https://warclash.io"},
{name:"WarClicker",url:"https://warclicker.io"},

{name:"WarHeroes",url:"https://warheroes.io"},
{name:"Warmerise",url:"https://warmerise.com"},
{name:"WarOfCells",url:"https://warofcells.io"},
{name:"WarScrap",url:"https://warscrap.io"},
{name:"WarSimulator",url:"https://warsimulator.io"},
{name:"WarTrains",url:"https://wartrains.io"},

{name:"WarZombies",url:"https://warzombies.io"},
{name:"WaterSort",url:"https://watersort.io"},
{name:"WaveRider",url:"https://waverider.io"},
{name:"WeBecomeWhatWeBehold",url:"https://webewhatwebehold.io"},
{name:"WebGLRacer",url:"https://webglracer.com"},
{name:"WebRacer",url:"https://webracer.io"},

{name:"WhackYourBoss",url:"https://whackyourboss.io"},
{name:"WhackYourEx",url:"https://whackyourex.io"},
{name:"WhackYourTeacher",url:"https://whackyourteacher.io"},
{name:"WheelieBike",url:"https://wheeliebike.io"},
{name:"WheelieChallenge",url:"https://wheeliechallenge.io"},
{name:"WheelieCross",url:"https://wheeliecross.io"},

{name:"WhiteTile",url:"https://whitetile.io"},
{name:"WildKratts",url:"https://wildkratts.io"},
{name:"Wilds.io",url:"https://wilds.io"},
{name:"WindRider",url:"https://windrider.io"},
{name:"WinterClash3D",url:"https://winterclash3d.io"},
{name:"WinterMoto",url:"https://wintermoto.io"},

{name:"Wipeout",url:"https://wipeout.io"},
{name:"Wizard101",url:"https://wizard101.com"},
{name:"WizardClash",url:"https://wizardclash.io"},
{name:"WizardRun",url:"https://wizardrun.io"},
{name:"Wolf3DClassic",url:"https://wolf3dclassic.com"},
{name:"WorldBox",url:"https://worldbox.io"},

{name:"WorldCraft",url:"https://worldcraft.io"},
{name:"WorldOfBlocks",url:"https://worldofblocks.io"},
{name:"WorldOfCars",url:"https://worldofcars.io"},
{name:"WorldOfWarships",url:"https://worldofwarships.com"},
{name:"WormRoyale",url:"https://wormroyale.io"},
{name:"WrestleJump",url:"https://wrestlejump.io"},
{name:"WrestleOnline",url:"https://wrestleonline.io"},
{name:"WrestleUp",url:"https://wrestleup.io"},
{name:"WrestlingLegends",url:"https://wrestlinglegends.io"},
{name:"WristRacer",url:"https://wristracer.io"},
{name:"XtremeDrift",url:"https://xtremedrift.io"},
{name:"XtremeRacers",url:"https://xtremeracers.io"},

{name:"XtremeSpeed",url:"https://xtremespeed.io"},
{name:"YachtDice",url:"https://yachtdice.io"},
{name:"YetiSports",url:"https://yetisports.io"},
{name:"YohohoArena",url:"https://yohohoarena.io"},
{name:"YouDrive",url:"https://youdrive.io"},
{name:"ZBall",url:"https://zball.io"},

{name:"ZBall2",url:"https://zball2.io"},
{name:"ZBall3",url:"https://zball3.io"},
{name:"ZEscape",url:"https://zescape.io"},
{name:"ZigZag",url:"https://zigzag.io"},
{name:"ZigZagRace",url:"https://zigzagrace.io"},
{name:"Zilch",url:"https://zilch.io"},

{name:"ZingSpeed",url:"https://zingspeed.io"},
{name:"Zlap.io",url:"https://zlap.io"},
{name:"ZombieArena",url:"https://zombiearena.io"},
{name:"ZombieAssault",url:"https://zombieassault.io"},
{name:"ZombieCraft",url:"https://zombiecraft.io"},
{name:"ZombieDerby",url:"https://zombiederby.io"},

{name:"ZombieDrive",url:"https://zombiedrive.io"},
{name:"ZombieEscape",url:"https://zombieescape.io"},
{name:"ZombieHunt",url:"https://zombiehunt.io"},
{name:"ZombieIdle",url:"https://zombieidle.io"},
{name:"ZombieKarts",url:"https://zombiekarts.io"},
{name:"ZombieLand",url:"https://zombieland.io"},

{name:"ZombieOutbreak",url:"https://zombieoutbreak.io"},
{name:"ZombiePlague",url:"https://zombieplague.io"},
{name:"ZombieReborn",url:"https://zombiereborn.io"},
{name:"ZombieRoad",url:"https://zombieroad.io"},
{name:"ZombieRoyale",url:"https://zombieroyale.io"},
{name:"ZombieRun",url:"https://zombierun.io"},

{name:"ZombieShooter",url:"https://zombieshooter.io"},
{name:"ZombieSiege",url:"https://zombiesiege.io"},
{name:"ZombieSlayer",url:"https://zombieslayer.io"},
{name:"ZombieSmash",url:"https://zombiesmash.io"},
{name:"ZombieSoccer",url:"https://zombiesoccer.io"},
{name:"ZombieSurvival",url:"https://zombiesurvival.io"},

{name:"ZombieTown",url:"https://zombietown.io"},
{name:"ZombieTrain",url:"https://zombietrain.io"},
{name:"ZombieTruck",url:"https://zombietruck.io"},
{name:"ZombieWars",url:"https://zombiewars.io"},
{name:"ZombieWave",url:"https://zombiewave.io"},
{name:"ZombieWorld",url:"https://zombieworld.io"},

{name:"ZomCraft",url:"https://zomcraft.io"},
{name:"ZomDefence",url:"https://zomdefence.io"},
{name:"ZomFight",url:"https://zomfight.io"},
{name:"ZomRush",url:"https://zomrush.io"},
{name:"ZomShoot",url:"https://zomshoot.io"},
{name:"ZomSurvivor",url:"https://zomsurvivor.io"},

{name:"ZomTower",url:"https://zomtower.io"},
{name:"ZomWars",url:"https://zomwars.io"},
{name:"ZType",url:"https://zty.pe"},
{name:"Zuma",url:"https://zuma.io"},
{name:"ZumaDeluxe",url:"https://zumadeluxe.io"},
{name:"Zygo",url:"https://zygo.io"},

{name:"AdventureQuest",url:"https://www.battleon.com"},
{name:"AQWorlds",url:"https://www.aq.com"},
{name:"DragonFable",url:"https://www.dragonfable.com"},
{name:"MechQuest",url:"https://www.mechquest.com"},
{name:"EpicDuel",url:"https://www.epicduel.com"},
{name:"SherwoodDungeon",url:"https://www.sherwooddungeon.com"},

{name:"RealmOfTheMadGod",url:"https://www.realmofthemadgod.com"},
{name:"BrowserQuest",url:"https://browserquest.com"},
{name:"MysteraLegacy",url:"https://www.mysteralegacy.com"},
{name:"TibiaME",url:"https://www.tibiame.com"},
{name:"MadWorldMMO",url:"https://madworldmmo.com"},
{name:"ArcaneLegends",url:"https://www.arcanelegendsgame.com"},

];
